/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.czechitas.java.spring.freemarker;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
